FROM nginx:1.19-alpine

# Install required packages
RUN apk add --update curl npm git

RUN echo "Node version: $(node --version)"
RUN echo "NPM version: $(npm --version)"
RUN echo "Git version: $(git --version)"

############
# Copy App #
############

# Copy app to container
COPY ./app /usr/src/app

# Check content of app folder
RUN ls -la /usr/src/app


#################
# Replace Paths #
#################

# Replace backend server paths
RUN cd /usr/src/app/src/ && \
    sed -i "s|VISUAL_ANALYTICS_ENGINE \?= \?\([\'\"]\)[^\'\"]\+[\'\"]|VISUAL_ANALYTICS_ENGINE = 'https://simsearch.dbvis.de/vae'|g" backend-urls.ts && \
    sed -i "s|JUPYTER_LAB \?= \?\([\'\"]\)[^\'\"]\+[\'\"]|JUPYTER_LAB = 'https://simsearch.dbvis.de/jupyter'|g" backend-urls.ts && \
    sed -i "s|V_PLOTS \?= \?\([\'\"]\)[^\'\"]\+[\'\"]|V_PLOTS = 'https://simsearch.dbvis.de/vplots'|g" backend-urls.ts && \
    cat backend-urls.ts

##############
# Bundle App #
##############

# Bundle app
RUN cd /usr/src/app && npm install && npm run-script build

# Move bundled webpage to webroot
RUN cp -a /usr/src/app/build/. /usr/share/nginx/html

# Cleanup
RUN rm -r /usr/src/app/*


###################
# Configure nginx #
###################

# Copy site configuration
COPY ./mysite.conf /etc/nginx/conf.d/default.conf

# Test config syntax and debug
RUN nginx -T

# Check content of webroot
RUN ls -la /usr/share/nginx/html/
